const libraryCore = [
  { file: "islam-and-making-nation", pdf: "islam-and-the-making-of-the-nation-formichi.pdf", cover: "islam-and-the-making-of-the-nation-title-page.png", title: "Islam and the Making of the Nation", author: "Chiara Formichi", publisher: "Brill", year: "2012", language: "English", description: "This monograph examines the political career and ideology of Sekarmadji Maridjan Kartosuwiryo, the Darul Islam movement, and the changing place of political Islam in Indonesia.", isbn: "9789004260467" },
  { file: "islam-in-process", pdf: "1007620.pdf", cover: "1007620-title-page.png", title: "Islam in Process", author: "Johann P. Arnason, Armando Salvatore & Georg Stauth (eds.)", publisher: "transcript Verlag", year: "2007", language: "English", description: "Comparative and historical perspectives on Islam as a religion and civilization.", isbn: "9783899424911" },
  { file: "study-of-shii-islam", title: "The Study of Shi'i Islam", author: "Gurdofarid Miskinzoda & Farhad Daftary (eds.)", publisher: "Bloomsbury Academic / I.B. Tauris", year: "2014", language: "English", description: "A reference work on Shi'i history, Qur'anic interpretation, law, authority, theology, ritual, and intellectual traditions." },
  { file: "between-islamic-secular-law", pdf: "between-islamic-and-secular-law.pdf", title: "Between Islamic and Secular Law", author: "Arezoo Sang Bastian", publisher: "sui generis Verlag", year: "2024", language: "English", description: "An analysis of organ-transplantation law in the Middle East and North Africa." },
  { file: "islamic-ethics-trusteeship-paradigm", title: "Islamic Ethics and the Trusteeship Paradigm", author: "Mohammed Hashas & Mutaz al-Khatib (eds.)", publisher: "Brill", year: "2021", language: "English", description: "Essays on Taha Abderrahmane's trusteeship paradigm across philosophy, theology, law, society, and biomedical ethics." },
  { file: "rethinking-islam-in-europe", title: "Rethinking Islam in Europe", author: "Zekirija Sejdini", publisher: "De Gruyter", year: "2022", language: "English", description: "A context-sensitive approach to Islamic theology and religious education in Europe." },
  { file: "malaika-seven-heavens", title: "Malaika and the Seven Heavens", author: "Toyin Omoyeni Falola", publisher: "University of Michigan Press", year: "2025", language: "English", description: "A memoir of Islam as lived in Ibadan and across Nigeria." },
  { file: "multipolar-early-christian-arabic", title: "A Multipolar Approach to Early Christian Arabic", author: "Phillip W. Stokes", publisher: "Open Book Publishers", year: "2026", language: "English", description: "A linguistic study of an early Arabic Gospel manuscript in the early Islamic-era landscape." },
  { file: "arabic-fable", title: "The Arabic Fable", author: "Ulrich Marzolph", publisher: "De Gruyter", year: "2025", language: "English", description: "An annotated inventory of fables from premodern Arabic literature." },
  { file: "arabic-in-context", title: "Arabic in Context", author: "Anthony J. Frendo & Kurstin Gatt (eds.)", publisher: "Peeters", year: "2024", language: "English" },
  { file: "9789004435544", title: "Handbook of Islamic Sects and Movements", author: "Muhammad Afzal Upal & Carole M. Cusack (eds.)", publisher: "Brill", year: "2021", language: "English" },
  { file: "abul-fadl-islam-middle-east-1990", title: "Islam and the Middle East", author: "Mona Abul-Fadl", publisher: "IIIT", year: "1990", language: "English" },
  { file: "islamic-and-muslim-studies-in-australia", title: "Islamic and Muslim Studies in Australia", author: "Halim Rane (ed.)", publisher: "Melbourne University Press", year: "2025", language: "English" },
  { file: "b-9780755649471", title: "The Renaissance of Shi'i Islam", author: "Farhad Daftary & Janis Esots (eds.)", publisher: "Bloomsbury Academic", year: "2022", language: "English" },
  { file: "9789004304864", title: "Islam and the Limits of the State", author: "R. Michael Feener, David Kloos & Annemarie Samuels (eds.)", publisher: "Brill", year: "2015", language: "English", isbn: "9789004304857 · 9789004304864" }
];

const libraryBatchTwo = [
  { file: "a-quest-for-true-islam", title: "A Quest for True Islam", author: "Rifki Rosyad", publisher: "ANU Press", year: "2007", doi: "10.26530/OAPEN_459476", source: "20.500.12657/33645", language: "English", description: "A study of contemporary Islamic life, authority, and reform in Indonesia." },
  { file: "dynamism-in-islamic-activism", title: "Dynamism in Islamic Activism", author: "Scientific Council for Government Policy", publisher: "Amsterdam University Press", year: "2006", doi: "10.5117/9789053569184", source: "20.500.12657/35182", language: "English", description: "An interdisciplinary examination of Islamic activism and its changing social and political forms." },
  { file: "modern-islamic-thinking-activism", title: "Modern Islamic Thinking and Activism", author: "Erkan Toguslu", publisher: "Leuven University Press", year: "2014", doi: "10.11116/MITA_CII", source: "20.500.12657/25961", language: "English", description: "Research on modern Muslim thought, civic engagement, and the forms of contemporary Islamic activism." },
  { file: "islamic-studies-21st-century", title: "Islamic Studies in the Twenty-first Century", author: "Edited by Léon Buskens & Annemarie van Sandwijk", publisher: "Amsterdam University Press", year: "2016", doi: "10.2307/j.ctt1zxsk97", source: "20.500.12657/30676", language: "English", description: "A collection reflecting on the methods, sources, and future directions of Islamic studies." },
  { file: "reformation-islamic-thought", title: "Reformation of Islamic Thought", author: "Scientific Council for Government Policy & Nasr Abû Zayd", publisher: "Amsterdam University Press", year: "2006", doi: "10.5117/9789053568286", source: "20.500.12657/35161", language: "English", description: "A discussion of renewal, interpretation, and reform in modern Islamic thought." },
  { file: "future-political-islam", title: "What Future for Political Islam", author: "G. Fuller & M. Kurpershoek", publisher: "WRR", year: "2004", doi: "10.26530/OAPEN_439826", source: "20.500.12657/34010", language: "English", description: "An analysis of political Islam and its possible trajectories in changing national and international contexts." },
  { file: "inclusive-welfare", title: "Inclusive Welfare", author: "Solikin M. Juhro, Ferry Syarifuddin & Ali Sakti", publisher: "Springer Nature", year: "2025", doi: "10.1007/978-981-96-0051-9", source: "20.500.12657/98596", language: "English", description: "An open-access study connecting welfare, inclusion, and Islamic economic thought." },
  { file: "islam-justice-democracy", title: "Islam, Justice, and Democracy", author: "Sabri Ciftci", publisher: "Temple University Press", year: "2021", source: "20.500.12657/52810", language: "English", description: "A study of Islam, political attitudes, justice, and democratic life." },
  { file: "arabic-dialogues", title: "Arabic Dialogues", author: "Rachel Mairs", publisher: "UCL Press", year: "2024", doi: "10.14324/111.9781800086180", source: "20.500.12657/87542", language: "English", description: "A study of Arabic language, texts, and cultural exchange across historical settings." }
];

libraryBatchTwo.push(
  { file: "arabic-in-contact", cover: "arabic-in-contact-cover.png", title: "Arabic in Contact", author: "Stefano Manfredi & Mauro Tosco", publisher: "John Benjamins Publishing Company", year: "2018", doi: "10.1075/sal.6", source: "20.500.12657/63282", language: "English", description: "Research on the linguistic consequences of Arabic contact with other languages." },
  { file: "arabic-contact-induced-change", cover: "arabic-contact-induced-change-cover.png", title: "Arabic and Contact-Induced Change", author: "Christopher Lucas & Stefano Manfredi", publisher: "Language Science Press", year: "2020", doi: "10.5281/zenodo.3744565", source: "20.500.12657/43774", language: "English", description: "A study of language contact and change in Arabic varieties." },
  { file: "latin-and-arabic", cover: "latin-and-arabic-cover.png", title: "Latin and Arabic", author: "Daniel G. König", publisher: "Heidelberg University Publishing", year: "2019", doi: "10.17885/heiup.448", source: "20.500.12657/22430", language: "English", description: "A history of exchange, translation, and encounter between Latin and Arabic textual traditions." },
  { file: "confronting-fascism-arabic-jewish-press", cover: "confronting-fascism-arabic-jewish-press-cover.png", title: "Confronting Fascism in the Arabic Jewish Press", author: "Lucia Admiraal", publisher: "Bloomsbury Academic", year: "2024", source: "20.500.12657/97994", language: "English", description: "A study of Arabic Jewish journalism and responses to fascism in the twentieth century." },
  { file: "transgressive-truths-flattering-lies", cover: "transgressive-truths-flattering-lies-cover.png", title: "Transgressive Truths and Flattering Lies", author: "Markus Schmitz", publisher: "transcript Verlag", year: "2020", doi: "10.14361/9783839450482", source: "20.500.12657/37420", language: "English", description: "Critical research on Arabic culture, literary expression, and political discourse." },
  { file: "teaching-learning-arabic-early-modern-europe", cover: "teaching-learning-arabic-early-modern-europe-cover.png", title: "The Teaching and Learning of Arabic in Early Modern Europe", author: "Edited by Jan Loop, Alastair Hamilton & Charles Burnett", publisher: "Brill", year: "2017", doi: "10.1163/9789004338623", source: "20.500.12657/29649", language: "English", description: "An account of Arabic scholarship, instruction, and knowledge transmission in early modern Europe." },
  { file: "stateless-citizenship", cover: "stateless-citizenship-cover.png", title: "Stateless Citizenship", author: "Shourideh C. Molavi", publisher: "Brill", year: "2013", source: "20.500.12657/29582", language: "English", description: "A study of citizenship, rights, and political belonging in the Middle East." },
  { file: "colonial-vocabularies", cover: "colonial-vocabularies-cover.png", title: "Colonial Vocabularies", author: "Sarah Irving, Karène Sanchez-Summerer, Rachel Mairs & Lucia Admiraal", publisher: "Amsterdam University Press", year: "2025", doi: "10.5117/9789048560394", source: "20.500.12657/97258", language: "English", description: "Research on language, culture, and colonial knowledge in Arabic-speaking contexts." },
  { file: "creating-standards", cover: "creating-standards-cover.png", title: "Creating Standards", author: "Dmitry Bondarev, Alessandro Gori & Lameen Souag", publisher: "De Gruyter", year: "2019", doi: "10.1515/9783110639063", source: "20.500.12657/25043", language: "English", description: "A comparative study of linguistic and textual standardization, including Arabic traditions." },
  { file: "islamic-council-norway", cover: "islamic-council-norway-cover.png", title: "The Islamic Council of Norway and the Challenge of Representing Islam in Europe", author: "Olav Elgvin", publisher: "Brill", year: "2025", doi: "10.1163/9789004701144", source: "20.500.12657/105301", language: "English", description: "An examination of Muslim representation, institutions, and public life in Europe." }
);
libraryBatchTwo.push(
  {file:"ottoman-prisons",cover:"ottoman-prisons-cover.png",title:"Prisons in the Late Ottoman Empire",author:"Kent F. Schull",publisher:"Edinburgh University Press",year:"2014",doi:"10.3366/edinburgh/9780748641734.001.0001",source:"20.500.12657/30785",language:"English",description:"Ottoman legal and social history."},
  {file:"dragoman-renaissance",cover:"dragoman-renaissance-cover.png",title:"The Dragoman Renaissance",author:"E. Natalie Rothman",publisher:"Cornell University Press",year:"2021",doi:"10.7298/fxrs-fn65",source:"20.500.12657/47093",language:"English",description:"Cultural exchange in the Ottoman Mediterranean."},
  {file:"ottoman-plague",cover:"ottoman-plague-cover.png",title:"Plague, Quarantines and Geopolitics in the Ottoman Empire",author:"Birsen Bulmus",publisher:"Edinburgh University Press",year:"2005",source:"20.500.12657/31780",language:"English",description:"Ottoman public health and geopolitics."},
  {file:"jihad-islam-world-war",cover:"jihad-islam-world-war-cover.png",title:"Jihad and Islam in World War I",author:"Erik-Jan Zürcher",publisher:"Leiden University Press",year:"2016",doi:"10.26530/OAPEN_605452",source:"20.500.12657/37513",language:"English",description:"Islam and global conflict in World War I."},
  {file:"ottoman-cairo-documents",cover:"ottoman-cairo-documents-cover.png",title:"Ottoman-Era Documents from the Cairo Genizah",author:"Jane Hathaway",publisher:"Open Book Publishers",year:"2026",doi:"10.11647/OBP.0502",source:"20.500.12657/111808",language:"English",description:"Ottoman documentary history from Cairo."},
  {file:"ottoman-rulers-tombs",cover:"ottoman-rulers-tombs-cover.png",title:"Ottoman Rulers' Tombs",author:"Mehmet Fatih Demirhan",publisher:"Edizioni Ca' Foscari",year:"2013",source:"20.500.12657/115446",language:"English",description:"Ottoman architectural and cultural history."},
  {file:"dangerous-gifts",cover:"dangerous-gifts-cover.png",title:"Dangerous Gifts",author:"Ozan Ozavci",publisher:"Oxford University Press",year:"2021",doi:"10.1093/oso/9780198852964.001.0001",source:"20.500.12657/50696",language:"English",description:"Ottoman diplomacy and political history."},
  {file:"historicizing-sunni-islam",cover:"historicizing-sunni-islam-cover.png",title:"Historicizing Sunni Islam in the Ottoman Empire",author:"Tijana Krstić & Derin Terzioğlu",publisher:"Brill",year:"2021",doi:"10.1163/9789004440296",source:"20.500.12657/42547",language:"English",description:"Sunni Islam in Ottoman history."},
  {file:"brief-history-islam-europe",cover:"brief-history-islam-europe-cover.png",title:"A Brief History of Islam in Europe",author:"Maurits Berger",publisher:"Leiden University Press",year:"2014",doi:"10.24415/9789087281953",source:"20.500.12657/45613",language:"English",description:"Islamic history in Europe."},
  {file:"neo-ottomanism-emotions",cover:"neo-ottomanism-emotions-cover.png",title:"Neo-Ottomanism and the Politics of Emotions in Turkey",author:"Nagehan Tokdoğan",publisher:"Springer Nature",year:"2024",doi:"10.1007/978-3-031-48723-1",source:"20.500.12657/92298",language:"English",description:"Contemporary Turkish politics and Ottoman memory."}
);

libraryBatchTwo.push(
  { file: "placing-islam", cover: "placing-islam-cover-1080p.png", title: "Placing Islam", author: "Timur Hammond", publisher: "University of California Press", year: "2023", doi: "10.1525/luminos.153", source: "20.500.12657/63202", language: "English", description: "An open-access study of urban space, religious practice, and Islam." },
  { file: "islamic-ethics-incidental-findings", cover: "islamic-ethics-incidental-findings-cover-1080p.png", title: "Islamic Ethics and Incidental Findings", author: "Mohammed Ghaly", publisher: "Springer Nature", year: "2024", doi: "10.1007/978-3-031-59405-2", source: "20.500.12657/90927", language: "English", description: "Islamic bioethics and the ethics of incidental findings in medical research." },
  { file: "companion-muslim-ethics", cover: "companion-muslim-ethics-cover-1080p.png", title: "A Companion to Muslim Ethics", author: "Amyn Sajoo", publisher: "Bloomsbury Academic", year: "2012", doi: "10.5040/9780755611218", source: "20.500.12657/99187", language: "English", description: "A companion volume on ethical thought, practice, and debate in Muslim traditions." },
  { file: "psychological-themes-classical-islamic-literature", cover: "psychological-themes-classical-islamic-literature-cover-1080p.png", title: "Psychological Themes in Classical Islamic Literature", author: "Bilal Ali Ansari, Khalid Elzamzamy, Hooman Keshavarzi & Aamir Azhar Zaidi", publisher: "Brill", year: "2025", doi: "10.1163/9789004725201", source: "20.500.12657/101050", language: "English", description: "Research on psychological themes and concepts in classical Islamic texts." },
  { file: "islam-on-the-move", cover: "islam-on-the-move-cover-1080p.png", title: "Islam on the Move", author: "Farish A. Noor", publisher: "Taylor & Francis", year: "2025", doi: "10.4324/9781003698210", source: "20.500.12657/107879", language: "English", description: "A study of mobility, networks, and Muslim life across contemporary contexts." },
  { file: "routledge-handbook-global-islam-consumer-culture", cover: "routledge-handbook-global-islam-consumer-culture-cover-1080p.png", title: "The Routledge Handbook of Global Islam and Consumer Culture", author: "Birgit Krawietz & François Gauthier", publisher: "Taylor & Francis", year: "2024", doi: "10.4324/9781003152712", source: "20.500.12657/97875", language: "English", description: "A handbook on Muslim consumer cultures, markets, media, and everyday life." },
  { file: "baghdadi-judeo-arabic", cover: "baghdadi-judeo-arabic-cover-1080p.png", title: "Baghdadi Judeo-Arabic", author: "Assaf Bar-Moshe", publisher: "UCL Press", year: "2024", doi: "10.14324/111.9781800086616", source: "20.500.12657/94808", language: "English", description: "A linguistic study of Baghdadi Judeo-Arabic and its textual traditions." },
  { file: "islam-academic-practice", cover: "islam-academic-practice-cover-1080p.png", title: "Der Islam als akademische Praxis", author: "Lena Dreier", publisher: "Nomos", year: "2023", doi: "0.5771/9783987400513", source: "20.500.12657/94813", language: "German", description: "A study of Islam as an academic practice in contemporary scholarship." },
  { file: "galen-on-demonstration", cover: "galen-on-demonstration-cover-1080p.png", title: "Galen, On Demonstration", author: "Matyáš Havrda & Pauline Koetschet", publisher: "De Gruyter", year: "2025", doi: "10.1515/9783111571003", source: "20.500.12657/102338", language: "English", description: "A critical study of Galen and the Arabic intellectual traditions surrounding demonstration." },
  { file: "galen-hippocrates-arabic-version", cover: "galen-hippocrates-arabic-version-cover-1080p.png", title: "Galen's Commentary on Hippocrates' Epidemics VI: Arabic Version", author: "Uwe Vagelpohl", publisher: "De Gruyter", year: "2022", doi: "10.1515/9783110774986", source: "20.500.12657/61097", language: "English · Arabic", description: "An edition and study of the Arabic transmission of Galen's commentary on Hippocrates." }
);

libraryBatchTwo.push(
  { file: "persianate-world", cover: "persianate-world-cover-1080p.png", title: "The Persianate World", author: "Nile Green", publisher: "University of California Press", year: "2019", doi: "10.1525/luminos.64", source: "20.500.12657/43793", language: "English", description: "A study of Persianate cultures and their global historical connections." },
  { file: "india-persian-world-letters", cover: "india-persian-world-letters-cover-1080p.png", title: "India in the Persian World of Letters", author: "Arthur Dudney", publisher: "Oxford University Press", year: "2022", doi: "10.1093/oso/9780192857415.001.0001", source: "20.500.12657/56704", language: "English", description: "Persian literary culture and intellectual life in South Asia." },
  { file: "modern-spoken-persian", cover: "modern-spoken-persian-cover-1080p.png", title: "Modern Spoken Persian in Contemporary Iranian Novels", author: "Katarzyna Wąsala", publisher: "Brill", year: "2023", doi: "10.14220/9783737016384", source: "20.500.12657/105141", language: "English", description: "A linguistic study of modern Persian in Iranian literature." },
  { file: "subtle-meaning", cover: "subtle-meaning-cover-1080p.png", title: "The Subtle Meaning", author: "Alessia Dal Bianco", publisher: "Edizioni Ca' Foscari", year: "2024", doi: "10.30687/978-88-6969-781-4", source: "20.500.12657/115529", language: "English", description: "Persianate literary and cultural studies." },
  { file: "khwadaynamag", cover: "khwadaynamag-cover-1080p.png", title: "Khwadāynāmag: The Middle Persian Book of Kings", author: "Jaakko Hämeen-Anttila", publisher: "Brill", year: "2018", doi: "10.1163/9789004277649", source: "20.500.12657/37828", language: "English", description: "A study of the Middle Persian Book of Kings and its tradition." },
  { file: "father-persian-verse", cover: "father-persian-verse-cover-1080p.png", title: "Father of Persian Verse", author: "Sassan Tabatabai", publisher: "Leiden University Press", year: "2010", doi: "10.24415/9789087280925", source: "20.500.12657/31709", language: "English", description: "A study of formative Persian poetic traditions." },
  { file: "materials-persian-narrative", cover: "materials-persian-narrative-cover-1080p.png", title: "Materials for a History of the Persian Narrative Tradition", author: "Paola Orsatti", publisher: "Edizioni Ca' Foscari", year: "2019", doi: "10.30687/978-88-6969-354-0", source: "20.500.12657/114053", language: "English", description: "Source materials for the history of Persian narrative literature." },
  { file: "after-tomorrow-days", cover: "after-tomorrow-days-cover-1080p.png", title: "After Tomorrow the Days Disappear", author: "Hasan Sijzi & Rebecca Gould", publisher: "Northwestern University Press", year: "2016", source: "20.500.12657/49664", language: "English", description: "Persian literary translation and cultural history." },
  { file: "translating-wisdom", cover: "translating-wisdom-cover-1080p.png", title: "Translating Wisdom", author: "Shankar Nair", publisher: "University of California Press", year: "2020", doi: "10.1525/luminos.87", source: "20.500.12657/39715", language: "English", description: "Arabic and Persian translation, philosophy, and intellectual exchange." },
  { file: "music-thousand-years", cover: "music-thousand-years-cover-1080p.png", title: "Music of a Thousand Years", author: "Ann E. Lucas", publisher: "University of California Press", year: "2019", doi: "10.1525/luminos.78", source: "20.500.12657/43715", language: "English", description: "Music, history, and cultural life in the Persianate world." }
);

const libraryBatchThree = [
  { file: "islamic-traditions-cirebon", generatedCover: true, title: "The Islamic Traditions of Cirebon", author: "A. G. Muhaimin", publisher: "ANU Press", year: "2006", doi: "10.22459/ISC.11.2006", source: "20.500.12854/", language: "English", description: "Ibadat and adat among Javanese Muslims in Cirebon." },
  { file: "reformist-muslims-yogyakarta", generatedCover: true, title: "Reformist Muslims in a Yogyakarta Village", author: "Hyung-Jun Kim", publisher: "ANU Press", year: "2007", doi: "10.22459/RMYV.03.2007", source: "20.500.12854/", language: "English", description: "Islamic transformation and contemporary socio-religious life in Yogyakarta." },
  { file: "islamising-indonesia", generatedCover: true, title: "Islamising Indonesia", author: "Yon Machmudi", publisher: "ANU Press", year: "2008", doi: "10.22459/II.11.2008", source: "20.500.12854/", language: "English", description: "The rise of Jemaah Tarbiyah and the Prosperous Justice Party." },
  { file: "rituals-islamic-spirituality", generatedCover: true, title: "Rituals of Islamic Spirituality", author: "Arif Zamhari", publisher: "ANU Press", year: "2010", doi: "10.22459/RIS.07.2010", source: "20.500.12854/", language: "English", description: "A study of Majlis Dhikr groups in East Java." },
  { file: "struggling-for-umma", generatedCover: true, title: "Struggling for the Umma", author: "Endang Turmudi", publisher: "ANU Press", year: "2007", source: "20.500.12854/", language: "English", description: "Changing leadership roles of kiai in Jombang, East Java." },
  { file: "workshop-for-morality", generatedCover: true, title: "The Workshop for Morality", author: "Dindin Solahudin", publisher: "ANU Press", year: "2008", source: "20.500.12854/", language: "English", description: "Islamic creativity at Pesantren Daarut Tauhid in Bandung." },
  { file: "signs-of-the-wali", generatedCover: true, title: "Signs of the Wali", author: "Tommy Christomy", publisher: "ANU Press", year: "2008", source: "20.500.12854/", language: "English", description: "Narratives at sacred sites in Pamijahan, West Java." },
  { file: "struggle-shiis-indonesia", generatedCover: true, title: "The Struggle of the Shi'is in Indonesia", author: "Zulkifli Zulkifli", publisher: "ANU Press", year: "2013", source: "20.500.12854/", language: "English", description: "A study of Shi'i communities, authority, and religious life in Indonesia." },
  { file: "a-quest-for-true-islam", generatedCover: true, title: "A Quest for True Islam", author: "Rifki Rosyad", publisher: "ANU Press", year: "2007", doi: "10.26530/OAPEN_459476", source: "20.500.12657/33645", language: "English", description: "A study of contemporary Islamic life, authority, and reform in Indonesia." },
  { file: "dynamism-in-islamic-activism", generatedCover: true, title: "Dynamism in Islamic Activism", author: "Scientific Council for Government Policy", publisher: "Amsterdam University Press", year: "2006", doi: "10.5117/9789053569184", source: "20.500.12657/35182", language: "English", description: "An interdisciplinary examination of Islamic activism and its changing social and political forms." }
];

// The catalogue de-duplicates by stable file/slug before exposing records to pages.
window.AQIRILibrary = Array.from(new Map([...libraryCore, ...libraryBatchTwo, ...libraryBatchThree].map((book) => [book.file, book])).values());
