const libraryCore = [
  { file: "islam-and-making-nation", pdf: "islam-and-the-making-of-the-nation-formichi.pdf", cover: "islam-and-the-making-of-the-nation-title-page.png", title: "Islam and the Making of the Nation", author: "Chiara Formichi", publisher: "Brill", year: "2012", language: "English", description: "This monograph examines the political career and ideology of Sekarmadji Maridjan Kartosuwiryo, the Darul Islam movement, and the changing place of political Islam in Indonesia.", isbn: "9789004260467" },
  { file: "islam-in-process", pdf: "1007620.pdf", cover: "1007620-title-page.png", title: "Islam in Process", author: "Johann P. Arnason, Armando Salvatore & Georg Stauth (eds.)", publisher: "transcript Verlag", year: "2007", language: "English", description: "Comparative and historical perspectives on Islam as a religion and civilization.", isbn: "9783899424911" },
  { file: "study-of-shii-islam", title: "The Study of Shi'i Islam", author: "Gurdofarid Miskinzoda & Farhad Daftary (eds.)", publisher: "Bloomsbury Academic / I.B. Tauris", year: "2014", language: "English", description: "A reference work on Shi'i history, Qur'anic interpretation, law, authority, theology, ritual, and intellectual traditions." },
  { file: "between-islamic-secular-law", pdf: "between-islamic-and-secular-law.pdf", title: "Between Islamic and Secular Law", author: "Arezoo Sang Bastian", publisher: "sui generis Verlag", year: "2024", language: "English", description: "An analysis of organ-transplantation law in the Middle East and North Africa." },
  { file: "islamic-ethics-trusteeship-paradigm", title: "Islamic Ethics and the Trusteeship Paradigm", author: "Mohammed Hashas & Mutaz al-Khatib (eds.)", publisher: "Brill", year: "2021", language: "English", description: "Essays on Taha Abderrahmane's trusteeship paradigm across philosophy, theology, law, society, and biomedical ethics." },
  { file: "rethinking-islam-in-europe", title: "Rethinking Islam in Europe", author: "Zekirija Sejdini", publisher: "De Gruyter", year: "2022", language: "English", description: "A context-sensitive approach to Islamic theology and religious education in Europe." },
  { file: "malaika-seven-heavens", title: "Malaika and the Seven Heavens", author: "Toyin Omoyeni Falola", publisher: "University of Michigan Press", year: "2025", language: "English", description: "A memoir of Islam as lived in Ibadan and across Nigeria." },
  { file: "multipolar-early-christian-arabic", title: "A Multipolar Approach to Early Christian Arabic", author: "Phillip W. Stokes", publisher: "Open Book Publishers", year: "2026", language: "English", description: "A linguistic study of an early Arabic Gospel manuscript in the early Islamic-era landscape." },
  { file: "arabic-fable", title: "The Arabic Fable", author: "Ulrich Marzolph", publisher: "De Gruyter", year: "2025", language: "English", description: "An annotated inventory of fables from premodern Arabic literature." },
  { file: "arabic-in-context", title: "Arabic in Context", author: "Anthony J. Frendo & Kurstin Gatt (eds.)", publisher: "Peeters", year: "2024", language: "English", description: "This edited English-language volume places Arabic language study within historical, cultural, and scholarly settings. It brings together work concerned with Arabic in context rather than as an isolated linguistic system. The collection is relevant to readers interested in Arabic studies, textual cultures, and the relationships between language, history, and interpretation." },
  { file: "9789004435544", title: "Handbook of Islamic Sects and Movements", author: "Muhammad Afzal Upal & Carole M. Cusack (eds.)", publisher: "Brill", year: "2021", language: "English", description: "This edited handbook provides a broad scholarly reference to Islamic sects and movements. Its scope supports comparative study of religious communities, doctrines, institutions, and historical development. Published by Brill in English, it is suited to researchers and students seeking an organised introduction to diversity within Islamic traditions." },
  { file: "abul-fadl-islam-middle-east-1990", title: "Islam and the Middle East", author: "Mona Abul-Fadl", publisher: "IIIT", year: "1990", language: "English", description: "Mona Abul-Fadl's English-language study addresses Islam and the Middle East from the perspective of Islamic thought. Published by IIIT in 1990, it is a historical record of scholarly discussion about religion, culture, and the region. The volume is relevant to readers working on modern Muslim intellectual history and Middle Eastern studies." },
  { file: "islamic-and-muslim-studies-in-australia", title: "Islamic and Muslim Studies in Australia", author: "Halim Rane (ed.)", publisher: "Melbourne University Press", year: "2025", language: "English", description: "Edited by Halim Rane, this English-language collection brings Islamic and Muslim studies into an Australian scholarly setting. Its title signals attention to the development, methods, and concerns of the field in Australia. Published by Melbourne University Press, it offers a recent reference for researchers interested in Islam, Muslims, and academic study in contemporary national contexts." },
  { file: "b-9780755649471", title: "The Renaissance of Shi'i Islam", author: "Farhad Daftary & Janis Esots (eds.)", publisher: "Bloomsbury Academic", year: "2022", language: "English", description: "This edited academic volume examines the idea of a renaissance within Shi'i Islam. The work is relevant to the study of Shi'i intellectual, religious, and cultural history, and its editorial format brings multiple scholarly perspectives together. Published in English by Bloomsbury Academic, it is intended for readers seeking research-oriented treatment of Shi'i traditions." },
  { file: "9789004304864", title: "Islam and the Limits of the State", author: "R. Michael Feener, David Kloos & Annemarie Samuels (eds.)", publisher: "Brill", year: "2015", language: "English", isbn: "9789004304857 · 9789004304864", description: "This English-language edited collection considers Islam alongside questions about the state and its limits. The volume is relevant to research on governance, political authority, law, and Muslim societies. Published by Brill in 2015, it offers a scholarly resource for readers examining how Islamic traditions and state institutions are discussed in contemporary academic work." }
];

const libraryBatchTwo = [
  { file: "a-quest-for-true-islam", title: "A Quest for True Islam", author: "Rifki Rosyad", publisher: "ANU Press", year: "2007", doi: "10.26530/OAPEN_459476", source: "20.500.12657/33645", language: "English", description: "A study of contemporary Islamic life, authority, and reform in Indonesia." },
  { file: "dynamism-in-islamic-activism", title: "Dynamism in Islamic Activism", author: "Scientific Council for Government Policy", publisher: "Amsterdam University Press", year: "2006", doi: "10.5117/9789053569184", source: "20.500.12657/35182", language: "English", description: "An interdisciplinary examination of Islamic activism and its changing social and political forms." },
  { file: "modern-islamic-thinking-activism", title: "Modern Islamic Thinking and Activism", author: "Erkan Toguslu", publisher: "Leuven University Press", year: "2014", doi: "10.11116/MITA_CII", source: "20.500.12657/25961", language: "English", description: "Research on modern Muslim thought, civic engagement, and the forms of contemporary Islamic activism." },
  { file: "islamic-studies-21st-century", title: "Islamic Studies in the Twenty-first Century", author: "Edited by Léon Buskens & Annemarie van Sandwijk", publisher: "Amsterdam University Press", year: "2016", doi: "10.2307/j.ctt1zxsk97", source: "20.500.12657/30676", language: "English", description: "A collection reflecting on the methods, sources, and future directions of Islamic studies." },
  { file: "reformation-islamic-thought", title: "Reformation of Islamic Thought", author: "Scientific Council for Government Policy & Nasr Abû Zayd", publisher: "Amsterdam University Press", year: "2006", doi: "10.5117/9789053568286", source: "20.500.12657/35161", language: "English", description: "A discussion of renewal, interpretation, and reform in modern Islamic thought." },
  { file: "future-political-islam", title: "What Future for Political Islam", author: "G. Fuller & M. Kurpershoek", publisher: "WRR", year: "2004", doi: "10.26530/OAPEN_439826", source: "20.500.12657/34010", language: "English", description: "An analysis of political Islam and its possible trajectories in changing national and international contexts." },
  { file: "inclusive-welfare", title: "Inclusive Welfare", author: "Solikin M. Juhro, Ferry Syarifuddin & Ali Sakti", publisher: "Springer Nature", year: "2025", doi: "10.1007/978-981-96-0051-9", source: "20.500.12657/98596", language: "English", description: "An open-access study connecting welfare, inclusion, and Islamic economic thought." },
  { file: "islam-justice-democracy", title: "Islam, Justice, and Democracy", author: "Sabri Ciftci", publisher: "Temple University Press", year: "2021", source: "20.500.12657/52810", language: "English", description: "A study of Islam, political attitudes, justice, and democratic life." },
  { file: "arabic-dialogues", title: "Arabic Dialogues", author: "Rachel Mairs", publisher: "UCL Press", year: "2024", doi: "10.14324/111.9781800086180", source: "20.500.12657/87542", language: "English", description: "A study of Arabic language, texts, and cultural exchange across historical settings." }
];

libraryBatchTwo.push(
  { file: "arabic-in-contact", cover: "arabic-in-contact-cover.png", title: "Arabic in Contact", author: "Stefano Manfredi & Mauro Tosco", publisher: "John Benjamins Publishing Company", year: "2018", doi: "10.1075/sal.6", source: "20.500.12657/63282", language: "English", description: "Research on the linguistic consequences of Arabic contact with other languages." },
  { file: "arabic-contact-induced-change", cover: "arabic-contact-induced-change-cover.png", title: "Arabic and Contact-Induced Change", author: "Christopher Lucas & Stefano Manfredi", publisher: "Language Science Press", year: "2020", doi: "10.5281/zenodo.3744565", source: "20.500.12657/43774", language: "English", description: "A study of language contact and change in Arabic varieties." },
  { file: "latin-and-arabic", cover: "latin-and-arabic-cover.png", title: "Latin and Arabic", author: "Daniel G. König", publisher: "Heidelberg University Publishing", year: "2019", doi: "10.17885/heiup.448", source: "20.500.12657/22430", language: "English", description: "A history of exchange, translation, and encounter between Latin and Arabic textual traditions." },
  { file: "confronting-fascism-arabic-jewish-press", cover: "confronting-fascism-arabic-jewish-press-cover.png", title: "Confronting Fascism in the Arabic Jewish Press", author: "Lucia Admiraal", publisher: "Bloomsbury Academic", year: "2024", source: "20.500.12657/97994", language: "English", description: "A study of Arabic Jewish journalism and responses to fascism in the twentieth century." },
  { file: "transgressive-truths-flattering-lies", cover: "transgressive-truths-flattering-lies-cover.png", title: "Transgressive Truths and Flattering Lies", author: "Markus Schmitz", publisher: "transcript Verlag", year: "2020", doi: "10.14361/9783839450482", source: "20.500.12657/37420", language: "English", description: "Critical research on Arabic culture, literary expression, and political discourse." },
  { file: "teaching-learning-arabic-early-modern-europe", cover: "teaching-learning-arabic-early-modern-europe-cover.png", title: "The Teaching and Learning of Arabic in Early Modern Europe", author: "Edited by Jan Loop, Alastair Hamilton & Charles Burnett", publisher: "Brill", year: "2017", doi: "10.1163/9789004338623", source: "20.500.12657/29649", language: "English", description: "An account of Arabic scholarship, instruction, and knowledge transmission in early modern Europe." },
  { file: "stateless-citizenship", cover: "stateless-citizenship-cover.png", title: "Stateless Citizenship", author: "Shourideh C. Molavi", publisher: "Brill", year: "2013", source: "20.500.12657/29582", language: "English", description: "A study of citizenship, rights, and political belonging in the Middle East." },
  { file: "colonial-vocabularies", cover: "colonial-vocabularies-cover.png", title: "Colonial Vocabularies", author: "Sarah Irving, Karène Sanchez-Summerer, Rachel Mairs & Lucia Admiraal", publisher: "Amsterdam University Press", year: "2025", doi: "10.5117/9789048560394", source: "20.500.12657/97258", language: "English", description: "Research on language, culture, and colonial knowledge in Arabic-speaking contexts." },
  { file: "creating-standards", cover: "creating-standards-cover.png", title: "Creating Standards", author: "Dmitry Bondarev, Alessandro Gori & Lameen Souag", publisher: "De Gruyter", year: "2019", doi: "10.1515/9783110639063", source: "20.500.12657/25043", language: "English", description: "A comparative study of linguistic and textual standardization, including Arabic traditions." },
  { file: "islamic-council-norway", cover: "islamic-council-norway-cover.png", title: "The Islamic Council of Norway and the Challenge of Representing Islam in Europe", author: "Olav Elgvin", publisher: "Brill", year: "2025", doi: "10.1163/9789004701144", source: "20.500.12657/105301", language: "English", description: "An examination of Muslim representation, institutions, and public life in Europe." }
);
libraryBatchTwo.push(
  {file:"ottoman-prisons",cover:"ottoman-prisons-cover.png",title:"Prisons in the Late Ottoman Empire",author:"Kent F. Schull",publisher:"Edinburgh University Press",year:"2014",doi:"10.3366/edinburgh/9780748641734.001.0001",source:"20.500.12657/30785",language:"English",description:"Ottoman legal and social history."},
  {file:"dragoman-renaissance",cover:"dragoman-renaissance-cover.png",title:"The Dragoman Renaissance",author:"E. Natalie Rothman",publisher:"Cornell University Press",year:"2021",doi:"10.7298/fxrs-fn65",source:"20.500.12657/47093",language:"English",description:"Cultural exchange in the Ottoman Mediterranean."},
  {file:"ottoman-plague",cover:"ottoman-plague-cover.png",title:"Plague, Quarantines and Geopolitics in the Ottoman Empire",author:"Birsen Bulmus",publisher:"Edinburgh University Press",year:"2005",source:"20.500.12657/31780",language:"English",description:"Ottoman public health and geopolitics."},
  {file:"jihad-islam-world-war",cover:"jihad-islam-world-war-cover.png",title:"Jihad and Islam in World War I",author:"Erik-Jan Zürcher",publisher:"Leiden University Press",year:"2016",doi:"10.26530/OAPEN_605452",source:"20.500.12657/37513",language:"English",description:"Islam and global conflict in World War I."},
  {file:"ottoman-cairo-documents",cover:"ottoman-cairo-documents-cover.png",title:"Ottoman-Era Documents from the Cairo Genizah",author:"Jane Hathaway",publisher:"Open Book Publishers",year:"2026",doi:"10.11647/OBP.0502",source:"20.500.12657/111808",language:"English",description:"Ottoman documentary history from Cairo."},
  {file:"ottoman-rulers-tombs",cover:"ottoman-rulers-tombs-cover.png",title:"Ottoman Rulers' Tombs",author:"Mehmet Fatih Demirhan",publisher:"Edizioni Ca' Foscari",year:"2013",source:"20.500.12657/115446",language:"English",description:"Ottoman architectural and cultural history."},
  {file:"dangerous-gifts",cover:"dangerous-gifts-cover.png",title:"Dangerous Gifts",author:"Ozan Ozavci",publisher:"Oxford University Press",year:"2021",doi:"10.1093/oso/9780198852964.001.0001",source:"20.500.12657/50696",language:"English",description:"Ottoman diplomacy and political history."},
  {file:"historicizing-sunni-islam",cover:"historicizing-sunni-islam-cover.png",title:"Historicizing Sunni Islam in the Ottoman Empire",author:"Tijana Krstić & Derin Terzioğlu",publisher:"Brill",year:"2021",doi:"10.1163/9789004440296",source:"20.500.12657/42547",language:"English",description:"Sunni Islam in Ottoman history."},
  {file:"brief-history-islam-europe",cover:"brief-history-islam-europe-cover.png",title:"A Brief History of Islam in Europe",author:"Maurits Berger",publisher:"Leiden University Press",year:"2014",doi:"10.24415/9789087281953",source:"20.500.12657/45613",language:"English",description:"Islamic history in Europe."},
  {file:"neo-ottomanism-emotions",cover:"neo-ottomanism-emotions-cover.png",title:"Neo-Ottomanism and the Politics of Emotions in Turkey",author:"Nagehan Tokdoğan",publisher:"Springer Nature",year:"2024",doi:"10.1007/978-3-031-48723-1",source:"20.500.12657/92298",language:"English",description:"Contemporary Turkish politics and Ottoman memory."}
);

libraryBatchTwo.push(
  { file: "placing-islam", cover: "placing-islam-cover-1080p.png", title: "Placing Islam", author: "Timur Hammond", publisher: "University of California Press", year: "2023", doi: "10.1525/luminos.153", source: "20.500.12657/63202", language: "English", description: "An open-access study of urban space, religious practice, and Islam." },
  { file: "islamic-ethics-incidental-findings", cover: "islamic-ethics-incidental-findings-cover-1080p.png", title: "Islamic Ethics and Incidental Findings", author: "Mohammed Ghaly", publisher: "Springer Nature", year: "2024", doi: "10.1007/978-3-031-59405-2", source: "20.500.12657/90927", language: "English", description: "Islamic bioethics and the ethics of incidental findings in medical research." },
  { file: "companion-muslim-ethics", cover: "companion-muslim-ethics-cover-1080p.png", title: "A Companion to Muslim Ethics", author: "Amyn Sajoo", publisher: "Bloomsbury Academic", year: "2012", doi: "10.5040/9780755611218", source: "20.500.12657/99187", language: "English", description: "A companion volume on ethical thought, practice, and debate in Muslim traditions." },
  { file: "psychological-themes-classical-islamic-literature", cover: "psychological-themes-classical-islamic-literature-cover-1080p.png", title: "Psychological Themes in Classical Islamic Literature", author: "Bilal Ali Ansari, Khalid Elzamzamy, Hooman Keshavarzi & Aamir Azhar Zaidi", publisher: "Brill", year: "2025", doi: "10.1163/9789004725201", source: "20.500.12657/101050", language: "English", description: "Research on psychological themes and concepts in classical Islamic texts." },
  { file: "islam-on-the-move", cover: "islam-on-the-move-cover-1080p.png", title: "Islam on the Move", author: "Farish A. Noor", publisher: "Taylor & Francis", year: "2025", doi: "10.4324/9781003698210", source: "20.500.12657/107879", language: "English", description: "A study of mobility, networks, and Muslim life across contemporary contexts." },
  { file: "routledge-handbook-global-islam-consumer-culture", cover: "routledge-handbook-global-islam-consumer-culture-cover-1080p.png", title: "The Routledge Handbook of Global Islam and Consumer Culture", author: "Birgit Krawietz & François Gauthier", publisher: "Taylor & Francis", year: "2024", doi: "10.4324/9781003152712", source: "20.500.12657/97875", language: "English", description: "A handbook on Muslim consumer cultures, markets, media, and everyday life." },
  { file: "baghdadi-judeo-arabic", cover: "baghdadi-judeo-arabic-cover-1080p.png", title: "Baghdadi Judeo-Arabic", author: "Assaf Bar-Moshe", publisher: "UCL Press", year: "2024", doi: "10.14324/111.9781800086616", source: "20.500.12657/94808", language: "English", description: "A linguistic study of Baghdadi Judeo-Arabic and its textual traditions." },
  { file: "islam-academic-practice", cover: "islam-academic-practice-cover-1080p.png", title: "Der Islam als akademische Praxis", author: "Lena Dreier", publisher: "Nomos", year: "2023", doi: "0.5771/9783987400513", source: "20.500.12657/94813", language: "German", description: "A study of Islam as an academic practice in contemporary scholarship." },
  { file: "galen-on-demonstration", cover: "galen-on-demonstration-cover-1080p.png", title: "Galen, On Demonstration", author: "Matyáš Havrda & Pauline Koetschet", publisher: "De Gruyter", year: "2025", doi: "10.1515/9783111571003", source: "20.500.12657/102338", language: "English", description: "A critical study of Galen and the Arabic intellectual traditions surrounding demonstration." },
  { file: "galen-hippocrates-arabic-version", cover: "galen-hippocrates-arabic-version-cover-1080p.png", title: "Galen's Commentary on Hippocrates' Epidemics VI: Arabic Version", author: "Uwe Vagelpohl", publisher: "De Gruyter", year: "2022", doi: "10.1515/9783110774986", source: "20.500.12657/61097", language: "English · Arabic", description: "An edition and study of the Arabic transmission of Galen's commentary on Hippocrates." }
);

libraryBatchTwo.push(
  { file: "persianate-world", cover: "persianate-world-cover-1080p.png", title: "The Persianate World", author: "Nile Green", publisher: "University of California Press", year: "2019", doi: "10.1525/luminos.64", source: "20.500.12657/43793", language: "English", description: "A study of Persianate cultures and their global historical connections." },
  { file: "india-persian-world-letters", cover: "india-persian-world-letters-cover-1080p.png", title: "India in the Persian World of Letters", author: "Arthur Dudney", publisher: "Oxford University Press", year: "2022", doi: "10.1093/oso/9780192857415.001.0001", source: "20.500.12657/56704", language: "English", description: "Persian literary culture and intellectual life in South Asia." },
  { file: "modern-spoken-persian", cover: "modern-spoken-persian-cover-1080p.png", title: "Modern Spoken Persian in Contemporary Iranian Novels", author: "Katarzyna Wąsala", publisher: "Brill", year: "2023", doi: "10.14220/9783737016384", source: "20.500.12657/105141", language: "English", description: "A linguistic study of modern Persian in Iranian literature." },
  { file: "subtle-meaning", cover: "subtle-meaning-cover-1080p.png", title: "The Subtle Meaning", author: "Alessia Dal Bianco", publisher: "Edizioni Ca' Foscari", year: "2024", doi: "10.30687/978-88-6969-781-4", source: "20.500.12657/115529", language: "English", description: "Persianate literary and cultural studies." },
  { file: "khwadaynamag", cover: "khwadaynamag-cover-1080p.png", title: "Khwadāynāmag: The Middle Persian Book of Kings", author: "Jaakko Hämeen-Anttila", publisher: "Brill", year: "2018", doi: "10.1163/9789004277649", source: "20.500.12657/37828", language: "English", description: "A study of the Middle Persian Book of Kings and its tradition." },
  { file: "father-persian-verse", cover: "father-persian-verse-cover-1080p.png", title: "Father of Persian Verse", author: "Sassan Tabatabai", publisher: "Leiden University Press", year: "2010", doi: "10.24415/9789087280925", source: "20.500.12657/31709", language: "English", description: "A study of formative Persian poetic traditions." },
  { file: "materials-persian-narrative", cover: "materials-persian-narrative-cover-1080p.png", title: "Materials for a History of the Persian Narrative Tradition", author: "Paola Orsatti", publisher: "Edizioni Ca' Foscari", year: "2019", doi: "10.30687/978-88-6969-354-0", source: "20.500.12657/114053", language: "English", description: "Source materials for the history of Persian narrative literature." },
  { file: "after-tomorrow-days", cover: "after-tomorrow-days-cover-1080p.png", title: "After Tomorrow the Days Disappear", author: "Hasan Sijzi & Rebecca Gould", publisher: "Northwestern University Press", year: "2016", source: "20.500.12657/49664", language: "English", description: "Persian literary translation and cultural history." },
  { file: "translating-wisdom", cover: "translating-wisdom-cover-1080p.png", title: "Translating Wisdom", author: "Shankar Nair", publisher: "University of California Press", year: "2020", doi: "10.1525/luminos.87", source: "20.500.12657/39715", language: "English", description: "Arabic and Persian translation, philosophy, and intellectual exchange." },
  { file: "music-thousand-years", cover: "music-thousand-years-cover-1080p.png", title: "Music of a Thousand Years", author: "Ann E. Lucas", publisher: "University of California Press", year: "2019", doi: "10.1525/luminos.78", source: "20.500.12657/43715", language: "English", description: "Music, history, and cultural life in the Persianate world." }
);

const libraryBatchThree = [
  { file: "islamic-traditions-cirebon", generatedCover: true, title: "The Islamic Traditions of Cirebon", author: "A. G. Muhaimin", publisher: "ANU Press", year: "2006", doi: "10.22459/ISC.11.2006", source: "20.500.12854/", language: "English", description: "Ibadat and adat among Javanese Muslims in Cirebon." },
  { file: "reformist-muslims-yogyakarta", generatedCover: true, title: "Reformist Muslims in a Yogyakarta Village", author: "Hyung-Jun Kim", publisher: "ANU Press", year: "2007", doi: "10.22459/RMYV.03.2007", source: "20.500.12854/", language: "English", description: "Islamic transformation and contemporary socio-religious life in Yogyakarta." },
  { file: "islamising-indonesia", generatedCover: true, title: "Islamising Indonesia", author: "Yon Machmudi", publisher: "ANU Press", year: "2008", doi: "10.22459/II.11.2008", source: "20.500.12854/", language: "English", description: "The rise of Jemaah Tarbiyah and the Prosperous Justice Party." },
  { file: "rituals-islamic-spirituality", generatedCover: true, title: "Rituals of Islamic Spirituality", author: "Arif Zamhari", publisher: "ANU Press", year: "2010", doi: "10.22459/RIS.07.2010", source: "20.500.12854/", language: "English", description: "A study of Majlis Dhikr groups in East Java." },
  { file: "struggling-for-umma", generatedCover: true, title: "Struggling for the Umma", author: "Endang Turmudi", publisher: "ANU Press", year: "2007", source: "20.500.12854/", language: "English", description: "Changing leadership roles of kiai in Jombang, East Java." },
  { file: "workshop-for-morality", generatedCover: true, title: "The Workshop for Morality", author: "Dindin Solahudin", publisher: "ANU Press", year: "2008", source: "20.500.12854/", language: "English", description: "Islamic creativity at Pesantren Daarut Tauhid in Bandung." },
  { file: "signs-of-the-wali", generatedCover: true, title: "Signs of the Wali", author: "Tommy Christomy", publisher: "ANU Press", year: "2008", source: "20.500.12854/", language: "English", description: "Narratives at sacred sites in Pamijahan, West Java." },
  { file: "struggle-shiis-indonesia", generatedCover: true, title: "The Struggle of the Shi'is in Indonesia", author: "Zulkifli Zulkifli", publisher: "ANU Press", year: "2013", source: "20.500.12854/", language: "English", description: "A study of Shi'i communities, authority, and religious life in Indonesia." },
  { file: "a-quest-for-true-islam", generatedCover: true, title: "A Quest for True Islam", author: "Rifki Rosyad", publisher: "ANU Press", year: "2007", doi: "10.26530/OAPEN_459476", source: "20.500.12657/33645", language: "English", description: "A study of contemporary Islamic life, authority, and reform in Indonesia." },
  { file: "dynamism-in-islamic-activism", generatedCover: true, title: "Dynamism in Islamic Activism", author: "Scientific Council for Government Policy", publisher: "Amsterdam University Press", year: "2006", doi: "10.5117/9789053569184", source: "20.500.12657/35182", language: "English", description: "An interdisciplinary examination of Islamic activism and its changing social and political forms." }
];

// Publisher-authorized open-access editions from the International Institute of Islamic Thought (IIIT).
// Each source URL is the publisher's record for the exact local PDF and cover used here.
const libraryBatchFour = [
  { file: "iiit-arts-islamic-civilization", pdf: "iiit-arts-islamic-civilization.pdf", cover: "iiit-arts-islamic-civilization-cover.jpg", title: "The Arts of Islamic Civilization", author: "Ismail Raji al-Faruqi", publisher: "International Institute of Islamic Thought", year: "2013", isbn: "978-1-56564-893-7", language: "English", category: "Islamic Civilisation", pages: "34", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/the-arts-of-islamic-civilization/", description: "This concise study relates Islamic artistic expression to the Qur'anic worldview. Al-Faruqi considers how tawhid informs visual form, pattern, space, and sound, and explains why the arts of Muslim societies should be read as cultural and aesthetic practices shaped by religious ideas. It is an accessible introduction to a foundational question in Islamic art history.", citation: "al-Faruqi, Ismail Raji. The Arts of Islamic Civilization. International Institute of Islamic Thought, 2013." },
  { file: "iiit-quranic-terminology", pdf: "iiit-quranic-terminology.pdf", cover: "iiit-quranic-terminology-cover.jpg", title: "Qur'anic Terminology: A Linguistic and Semantic Analysis", author: "Balil Abd Al-Karim", publisher: "International Institute of Islamic Thought", year: "2017", isbn: "978-1-56564-874-6", language: "English", category: "Qur'anic Studies", pages: "190", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/quranic-terminology-a-linguistic-and-semantic-analysis/", description: "A linguistic and semantic investigation of terms used in the Qur'an. The book approaches Qur'anic vocabulary through its Arabic usage and conceptual relationships, helping readers see how individual words function within wider patterns of meaning. It is particularly useful for students interested in the language of the Qur'an and methods of close textual interpretation.", citation: "Abd Al-Karim, Balil. Qur'anic Terminology: A Linguistic and Semantic Analysis. International Institute of Islamic Thought, 2017." },
  { file: "iiit-thematic-commentary-quran", pdf: "iiit-thematic-commentary-quran.pdf", cover: "iiit-thematic-commentary-quran-cover.jpg", title: "A Thematic Commentary on the Qur'an", author: "Shaykh Muhammad Al-Ghazali", publisher: "International Institute of Islamic Thought", year: "2000", isbn: "978-1-56564-502-8", language: "English", category: "Qur'anic Studies", pages: "816", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/a-thematic-commentary-on-the-quran/", description: "Muhammad al-Ghazali's commentary reads the Qur'an through its recurring ethical, social, and spiritual concerns. Rather than treating each verse in isolation, it draws connections across surahs and situates passages within their broader arguments. The English edition offers a substantial resource for readers seeking a thematic approach to Qur'anic interpretation and its treatment of contemporary moral questions.", citation: "Al-Ghazali, Muhammad. A Thematic Commentary on the Qur'an. International Institute of Islamic Thought, 2000." },
  { file: "iiit-quranic-worldview", pdf: "iiit-quranic-worldview.pdf", cover: "iiit-quranic-worldview-cover.jpg", title: "The Qur'anic Worldview: A Springboard for Cultural Reform", author: "AbdulHamid AbuSulayman", publisher: "International Institute of Islamic Thought", year: "2013", isbn: "978-1-56564-780-0", language: "English", category: "Qur'anic Studies", pages: "28", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/the-quranic-worldview/", description: "AbuSulayman outlines a Qur'an-centred framework for cultural renewal. He focuses on the relationship between revelation, reason, moral responsibility, and social action, arguing that a coherent worldview is necessary for reform. This short book introduces key themes in modern Islamic thought while remaining rooted in the Qur'an's ethical and intellectual orientation.", citation: "AbuSulayman, AbdulHamid. The Qur'anic Worldview: A Springboard for Cultural Reform. International Institute of Islamic Thought, 2013." },
  { file: "iiit-foundation-knowledge", pdf: "iiit-foundation-knowledge.pdf", cover: "iiit-foundation-knowledge-cover.jpg", title: "The Foundation of Knowledge: A Comparative Study in Islamic and Western Methods of Inquiry", author: "Louay Safi", publisher: "International Institute of Islamic Thought", year: "2014", isbn: "978-1-56564-898-2", language: "English", category: "Islamic Thought", pages: "216", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/the-foundation-of-knowledge/", description: "Louay Safi compares the intellectual premises and methods of inquiry associated with Islamic and Western traditions. The study examines revelation, reason, observation, and historical experience as sources of knowledge, then considers their methodological implications. It is a focused contribution to debates about epistemology, social science, and the renewal of Islamic intellectual practice.", citation: "Safi, Louay. The Foundation of Knowledge: A Comparative Study in Islamic and Western Methods of Inquiry. International Institute of Islamic Thought, 2014." },
  { file: "iiit-source-methodology-islamic-jurisprudence", pdf: "iiit-source-methodology-islamic-jurisprudence.pdf", cover: "iiit-source-methodology-islamic-jurisprudence-cover.jpg", title: "Source Methodology in Islamic Jurisprudence", subtitle: "Usul al-Fiqh al-Islami", author: "Taha Jabir Al-Alwani", publisher: "International Institute of Islamic Thought", year: "2003", isbn: "978-1-56564-882-1", language: "English", category: "Islamic Jurisprudence", pages: "96", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/source-methodology-in-islamic-jurisprudence/", description: "This introduction examines the sources and methodological questions of usul al-fiqh. Al-Alwani discusses the Qur'an, Sunnah, consensus, reasoning, and the relationship between legal method and changing circumstances. The work is suited to readers who want a concise scholarly overview of how jurists have approached the derivation and interpretation of Islamic legal rulings.", citation: "Al-Alwani, Taha Jabir. Source Methodology in Islamic Jurisprudence: Usul al-Fiqh al-Islami. International Institute of Islamic Thought, 2003." },
  { file: "iiit-islamic-thought-reform", pdf: "iiit-islamic-thought-reform.pdf", cover: "iiit-islamic-thought-reform-cover.jpg", title: "Islamic Thought: An Approach to Reform", author: "Taha Jabir Al-Alwani", publisher: "International Institute of Islamic Thought", year: "2006", isbn: "978-1-56564-548-6", language: "English", category: "Islamic Thought", pages: "192", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/islamic-thought-an-approach-to-reform/", description: "Al-Alwani addresses questions of reform in modern Islamic thought through the disciplines that shape interpretation, education, and public life. The book considers inherited modes of reasoning alongside contemporary intellectual challenges, with emphasis on a principled engagement with revelation and reality. It offers a sustained account of reform as a methodological rather than merely political undertaking.", citation: "Al-Alwani, Taha Jabir. Islamic Thought: An Approach to Reform. International Institute of Islamic Thought, 2006." },
  { file: "iiit-quran-normative-pluralism", pdf: "iiit-quran-normative-pluralism.pdf", cover: "iiit-quran-normative-pluralism-cover.jpg", title: "The Qur'an and Normative Religious Pluralism", subtitle: "A Thematic Study of the Qur'an", author: "Arif Kemil Abdullah", publisher: "International Institute of Islamic Thought", year: "2014", isbn: "978-1-56564-777-0", language: "English", category: "Qur'anic Studies", pages: "316", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/the-quran-and-normative-religious-pluralism/", description: "A thematic study of Qur'anic passages concerned with religious difference, human diversity, and relations among communities. Abdullah considers the interpretive principles that shape readings of these verses and asks how they inform a normative account of pluralism. The book provides a detailed resource for Qur'anic studies, theology, and contemporary discussions of interreligious coexistence.", citation: "Abdullah, Arif Kemil. The Qur'an and Normative Religious Pluralism: A Thematic Study of the Qur'an. International Institute of Islamic Thought, 2014." },
  { file: "iiit-al-shura-quranic-consultation", pdf: "iiit-al-shura-quranic-consultation.pdf", cover: "iiit-al-shura-quranic-consultation-cover.jpg", title: "Al-Shura: The Qur'anic Principle of Consultation", author: "Ahmad Al-Raysuni", publisher: "International Institute of Islamic Thought", isbn: "978-1-56564-504-2", language: "English", category: "Qur'anic Studies", pages: "206", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/al-shura-the-quranic-principle-of-consultation/", description: "Ahmad al-Raysuni studies shura as a Qur'anic principle and a concept in Islamic political and legal thought. The book examines relevant texts, historical interpretations, and the role of consultation in collective decision-making. It gives readers a careful grounding in the term's intellectual history and its continuing importance in discussions of governance and public ethics.", citation: "Al-Raysuni, Ahmad. Al-Shura: The Qur'anic Principle of Consultation. International Institute of Islamic Thought." },
  { file: "iiit-where-east-meets-west", pdf: "iiit-where-east-meets-west.pdf", cover: "iiit-where-east-meets-west-cover.jpg", title: "Where East Meets West", subtitle: "Appropriating the Islamic Encounter for a Spiritual-Cultural Revival", author: "Mona Abul-Fadl", publisher: "International Institute of Islamic Thought", year: "2010", isbn: "978-1-56564-796-1", language: "English", category: "Muslim Intellectual History", pages: "111", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/%e2%80%8bwhere-east-meets-west-appropriating-the-islamic-encounter-for-a-spiritual-cultural-revival/", description: "Mona Abul-Fadl reflects on encounters between Islamic and Western intellectual traditions and their implications for cultural renewal. She considers questions of civilization, knowledge, and spiritual orientation without reducing the relationship to simple opposition. The essays offer a historically informed perspective on cross-cultural exchange and the resources Islamic thought can bring to contemporary intellectual life.", citation: "Abul-Fadl, Mona. Where East Meets West: Appropriating the Islamic Encounter for a Spiritual-Cultural Revival. International Institute of Islamic Thought, 2010." },
  { file: "iiit-apostates-islam-freedom-faith", pdf: "iiit-apostates-islam-freedom-faith.pdf", cover: "iiit-apostates-islam-freedom-faith-cover.png", title: "Apostates, Islam & Freedom of Faith", subtitle: "Change of Conviction vs. Change of Allegiance", author: "AbdulHamid AbuSulayman", publisher: "International Institute of Islamic Thought", isbn: "978-1-56564-509-7", language: "English", category: "Islamic Thought", pages: "42", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/apostates-islam-freedom-of-faith-change-of-conviction-vs-change-%e2%80%8bof-%e2%80%8ballegiance-occasional-paper/", description: "This brief study distinguishes a personal change of religious conviction from political betrayal in discussions of apostasy. AbuSulayman reviews the concepts and historical assumptions that have shaped the debate, then frames freedom of faith as a matter requiring careful textual and contextual analysis. It is a concise source for the modern Islamic legal and ethical discussion.", citation: "AbuSulayman, AbdulHamid. Apostates, Islam & Freedom of Faith: Change of Conviction vs. Change of Allegiance. International Institute of Islamic Thought." },
  { file: "iiit-ifta-fatwa-muslim-world", pdf: "iiit-ifta-fatwa-muslim-world.pdf", cover: "iiit-ifta-fatwa-muslim-world-cover.jpg", title: "Ifta' and Fatwa in the Muslim World and the West", author: "Zulfiqar Ali Shah", publisher: "International Institute of Islamic Thought", year: "2014", isbn: "978-1-56564-538-7", language: "English", category: "Hadith and Islamic Law", pages: "204", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/ifta-and-fatwa-in-the-muslim-world-and-the-west/", description: "Zulfiqar Ali Shah examines ifta, the practice of issuing legal opinions, in both Muslim-majority and Western settings. The book discusses the authority of muftis, the methods and institutions of fatwa, and the challenges created by migration and minority contexts. It offers a comparative account of an important practice in contemporary Islamic legal life.", citation: "Shah, Zulfiqar Ali. Ifta' and Fatwa in the Muslim World and the West. International Institute of Islamic Thought, 2014." },
  { file: "iiit-islam-economic-development", pdf: "iiit-islam-economic-development.pdf", cover: "iiit-islam-economic-development-cover.jpg", title: "Islam and Economic Development", subtitle: "A Strategy for Development with Justice and Stability", author: "Muhammad Umer Chapra", publisher: "International Institute of Islamic Thought", year: "1993", isbn: "979-8-89193-204-3", language: "English", category: "Islamic Civilisation", pages: "186", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/islam-and-economic-development/", description: "Muhammad Umer Chapra sets out an Islamic approach to economic development that treats justice, moral responsibility, and social stability as integral rather than secondary concerns. He connects development policy to the ethical aims of Islam and considers institutional conditions for equitable growth. The book remains a useful reference for Islamic economics and modern Muslim intellectual history.", citation: "Chapra, Muhammad Umer. Islam and Economic Development: A Strategy for Development with Justice and Stability. International Institute of Islamic Thought, 1993." },
  { file: "iiit-issues-contemporary-islamic-thought", pdf: "iiit-issues-contemporary-islamic-thought.pdf", cover: "iiit-issues-contemporary-islamic-thought-cover.jpg", title: "Issues in Contemporary Islamic Thought", author: "Taha Jabir Al-Alwani", publisher: "International Institute of Islamic Thought", year: "2005", isbn: "978-1-56564-549-3", language: "English", category: "Islamic Thought", pages: "316", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/issues-in-contemporary-islamic-thought/", description: "This collection addresses major questions confronting modern Islamic thought, including methodology, legal reasoning, education, and the relationship between tradition and contemporary reality. Al-Alwani argues for intellectual renewal grounded in the Qur'an and Sunnah while attentive to changing social conditions. Its essays provide a broad entry point into debates over reform and Muslim public life.", citation: "Al-Alwani, Taha Jabir. Issues in Contemporary Islamic Thought. International Institute of Islamic Thought, 2005." },
  { file: "iiit-maqasid-ijtihad-civilization-renewal", pdf: "iiit-maqasid-ijtihad-civilization-renewal.pdf", cover: "iiit-maqasid-ijtihad-civilization-renewal-cover.jpg", title: "Maqasid Al-Shari'ah, Ijtihad and Civilization Renewal", author: "Mohammad Hashim Kamali", publisher: "International Institute of Islamic Thought", year: "2012", isbn: "978-1-56564-494-6", language: "English", category: "Islamic Jurisprudence", pages: "60", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/maqasid-al-shariah-ijtihad-and-civilization-renewal/", description: "Mohammad Hashim Kamali explains the relationship between maqasid al-shari'ah, ijtihad, and renewal in Muslim societies. He introduces the higher objectives of Islamic law and considers how purposive reasoning can guide contemporary legal and ethical reflection. This compact study is appropriate for readers seeking an academically grounded introduction to a central framework in modern Islamic jurisprudence.", citation: "Kamali, Mohammad Hashim. Maqasid Al-Shari'ah, Ijtihad and Civilization Renewal. International Institute of Islamic Thought, 2012." },
  { file: "iiit-variant-readings-quran", pdf: "iiit-variant-readings-quran.pdf", cover: "iiit-variant-readings-quran-cover.jpg", title: "Variant Readings of the Qur'an", subtitle: "A Critical Study of Their Historical and Linguistic Origins", author: "Ahmad Ali Al-Imam", publisher: "International Institute of Islamic Thought", year: "2006", isbn: "978-1-56564-795-4", language: "English", category: "Qur'anic Studies", pages: "188", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/variant-readings-of-the-quran-a-critical-study-of-their-historical-%e2%80%8band-linguistic-origins%e2%80%8b/", description: "Ahmad Ali al-Imam investigates the historical and linguistic origins of variant Qur'anic readings. The study introduces the transmission and classification of readings, then evaluates questions raised by their linguistic forms and historical setting. It provides an accessible scholarly treatment of qira'at for students of Qur'anic studies, Arabic linguistics, and the textual history of Islam.", citation: "Al-Imam, Ahmad Ali. Variant Readings of the Qur'an: A Critical Study of Their Historical and Linguistic Origins. International Institute of Islamic Thought, 2006." },
  { file: "iiit-islamic-vision-development-maqasid", pdf: "iiit-islamic-vision-development-maqasid.pdf", cover: "iiit-islamic-vision-development-maqasid-cover.jpg", title: "The Islamic Vision of Development in the Light of Maqasid al-Shari'ah", author: "Muhammad Umer Chapra", publisher: "International Institute of Islamic Thought", year: "2008", isbn: "979-8-89193-203-6", language: "English", category: "Islamic Thought", pages: "56", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/the-islamic-vision-of-development-in-the-light-of-maqasid-al-shariah/", description: "Chapra links development to the maqasid al-shari'ah, arguing that material progress must be assessed alongside moral, social, and human aims. He outlines an Islamic vision of development concerned with justice, dignity, family, knowledge, and good governance. The book offers a compact framework for connecting Islamic ethical thought with policy and development studies.", citation: "Chapra, Muhammad Umer. The Islamic Vision of Development in the Light of Maqasid al-Shari'ah. International Institute of Islamic Thought, 2008." },
  { file: "iiit-parameters-halal-haram", pdf: "iiit-parameters-halal-haram.pdf", cover: "iiit-parameters-halal-haram-cover.jpg", title: "The Parameters of Halal and Haram in Shariah and the Halal Industry", author: "Mohammad Hashim Kamali", publisher: "International Institute of Islamic Thought", year: "2013", isbn: "978-1-56564-776-3", language: "English", category: "Islamic Jurisprudence", pages: "66", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/the-parameters-of-halal-and-haram-in-shariah-and-the-halal-industry-occasional-papers-series-23/", description: "This study explains the legal and ethical categories of halal and haram and considers their application in the contemporary halal industry. Kamali addresses principles of interpretation, consumer practice, regulation, and certification without reducing the discussion to commercial labels. It is a concise guide to the jurisprudential foundations that inform current debates about halal standards.", citation: "Kamali, Mohammad Hashim. The Parameters of Halal and Haram in Shariah and the Halal Industry. International Institute of Islamic Thought, 2013." },
  { file: "iiit-fiqh-minorities", pdf: "iiit-fiqh-minorities.pdf", cover: "iiit-fiqh-minorities-cover.jpg", title: "Towards a Fiqh for Minorities", subtitle: "Some Basic Reflections", author: "Taha Jabir Al-Alwani", publisher: "International Institute of Islamic Thought", year: "2010", isbn: "978-1-56564-790-9", language: "English", category: "Islamic Jurisprudence", pages: "70", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/towards-a-fiqh-for-minorities-some-basic-reflections-2/", description: "Al-Alwani considers the legal and ethical questions faced by Muslim minorities living outside Muslim-majority societies. The book discusses context, citizenship, social participation, and the methods needed for responsible juristic reasoning. It is a foundational modern contribution to the discussion of fiqh al-aqalliyyat and the adaptation of legal thought to minority settings.", citation: "Al-Alwani, Taha Jabir. Towards a Fiqh for Minorities: Some Basic Reflections. International Institute of Islamic Thought, 2010." },
  { file: "iiit-sources-scientific-knowledge", pdf: "iiit-sources-scientific-knowledge.pdf", cover: "iiit-sources-scientific-knowledge-cover.jpg", title: "Sources of Scientific Knowledge", subtitle: "The Geological Concept of Mountains in the Qur'an", author: "Z. R. El-Naggar", publisher: "International Institute of Islamic Thought", year: "1991", isbn: "978-1-56564-067-2", language: "English", category: "Qur'anic Studies", pages: "100", access: "Publisher-designated open access", sourceUrl: "https://iiit.org/en/book/sources-of-scientific-knowledge/", description: "Z. R. El-Naggar examines Qur'anic references to mountains alongside geological concepts and scientific interpretation. The book forms part of a wider modern discussion about knowledge, scripture, and the natural world in Muslim intellectual discourse. It is included as a historical source for the study of twentieth-century Qur'anic interpretation and science-oriented commentary.", citation: "El-Naggar, Z. R. Sources of Scientific Knowledge: The Geological Concept of Mountains in the Qur'an. International Institute of Islamic Thought, 1991." }
];

// The catalogue de-duplicates by stable file/slug before exposing records to pages.
const libraryBatchFive = [
  {file:"iiit-crisis-muslim-mind",title:"Crisis in the Muslim Mind",author:"AbdulHamid A. AbuSulayman",publisher:"International Institute of Islamic Thought",year:"2004",isbn:"978-1-56564-532-5",language:"English",category:"Islamic Thought",pdf:"iiit-crisis-muslim-mind.pdf",cover:"iiit-crisis-muslim-mind-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/crisis-in-the-muslim-mind/",description:"AbuSulayman examines intellectual stagnation in modern Muslim societies and proposes renewal through a re-engagement with revelation, reason, and responsible social inquiry. The work situates reform within questions of education, methodology, and cultural confidence, making it a useful historical text for the study of twentieth-century Islamic reform thought."},
  {file:"iiit-faruqi-selected-essays",title:"Isma'il Al-Faruqi: Selected Essays",author:"Isma'il Al-Faruqi",publisher:"International Institute of Islamic Thought",year:"2018",isbn:"978-1-64205-207-7",language:"English",category:"Muslim Intellectual History",pdf:"iiit-faruqi-selected-essays.pdf",cover:"iiit-faruqi-selected-essays-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/ismail-al-faruq-selected-essays/",description:"This selection introduces al-Faruqi's writing on values, comparative religion, and the intellectual foundations of Islam. The essays illustrate his approach to questions that connect religious studies, culture, and modernity. It is a concise primary source for readers studying a major twentieth-century Muslim philosopher and the wider history of Islamic thought."},
  {file:"iiit-studies-islamic-civilization",title:"Studies in Islamic Civilization",subtitle:"The Muslim Contribution to the Renaissance",author:"Ahmed Essa & Othman Ali",publisher:"International Institute of Islamic Thought",year:"2010",isbn:"978-1-56564-885-2",language:"English",category:"Islamic Civilisation",pdf:"iiit-studies-islamic-civilization.pdf",cover:"iiit-studies-islamic-civilization-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/studies-in-islamic-civilization-the-muslim-contribution-to-the-renaissance-2/",description:"Essa and Ali survey Muslim contributions to scientific, literary, and intellectual life and their significance for European Renaissance narratives. The book connects institutions of learning, translation, and cultural exchange across the medieval Mediterranean. It provides an accessible, wide-ranging introduction to Islamic civilisation and its place in global intellectual history."},
  {file:"iiit-ijtihad-renewal",title:"Ijtihad and Renewal",author:"Said Shabbar",publisher:"International Institute of Islamic Thought",year:"2017",isbn:"978-1-56564-540-0",language:"English",category:"Islamic Jurisprudence",pdf:"iiit-ijtihad-renewal.pdf",cover:"iiit-ijtihad-renewal-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/ijtihad-and-renewal/",description:"Said Shabbar explores ijtihad as an intellectual practice needed for the renewal of Muslim thought. He considers the relationship between inherited legal reasoning, contemporary context, and the Qur'an and Sunnah. The book is a clear introduction to debates over independent reasoning and reform within modern Islamic jurisprudence."},
  {file:"iiit-actualization-maqasid",title:"Actualization of the Higher Purposes of Shariah",author:"Mohammad Hashim Kamali",publisher:"International Institute of Islamic Thought",year:"2020",isbn:"978-1-64205-345-6",language:"English",category:"Islamic Jurisprudence",pdf:"iiit-actualization-maqasid.pdf",cover:"iiit-actualization-maqasid-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/actualization-tafil-of-the-higher-purposes-maqasid-of-shariah/",description:"Kamali considers how maqasid al-shari'ah can inform practical legal and ethical reasoning. He discusses its relationship with the Qur'an, hadith, usul al-fiqh, human reason, and moral intuition. The work is a concise scholarly guide to applying the higher purposes of Islamic law without detaching them from established interpretive methods."},
  {file:"iiit-reading-signs",title:"Reading the Signs",subtitle:"A Qur'anic Perspective on Thinking",author:"Mohammad Hashim Kamali",publisher:"International Institute of Islamic Thought",year:"2018",isbn:"978-1-64205-234-3",language:"English",category:"Qur'anic Studies",pdf:"iiit-reading-signs.pdf",cover:"iiit-reading-signs-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/reading-the-signs-a-quranic-perspective-on-thinking/",description:"This study develops a Qur'anic account of thinking, rationality, and critical reflection through the idea of divine signs. Kamali discusses sources of knowledge, obstacles to sound reasoning, scientific creativity, and ijtihad. It offers an accessible perspective on the relationship between faith, moral purpose, and intellectual inquiry in Islamic thought."},
  {file:"iiit-contribution-islamic-thought-economics",title:"Contribution of Islamic Thought to Modern Economics",author:"Economic seminar held jointly by al-Azhar University and IIIT",publisher:"International Institute of Islamic Thought",year:"1998",isbn:"978-1-56564-531-8",language:"English",category:"Islamic Thought",pdf:"iiit-contribution-islamic-thought-economics.pdf",cover:"iiit-contribution-islamic-thought-economics-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/contribution-of-islamic-thought-to-modern-economics/",description:"Collected papers from a Cairo seminar consider the contribution of Islamic intellectual traditions to modern economic questions. The volume brings together perspectives on development, institutions, and the ethical dimensions of economic life. It is a documentary source for the history of Islamic economics and debates over the reform of economic knowledge."},
  {file:"iiit-marital-discord",title:"Marital Discord",subtitle:"Recapturing Human Dignity Through the Higher Objectives of Islamic Law",author:"AbdulHamid AbuSulayman",publisher:"International Institute of Islamic Thought",year:"2008",isbn:"978-1-56564-496-0",language:"English",category:"Islamic Jurisprudence",pdf:"iiit-marital-discord.pdf",cover:"iiit-marital-discord-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/marital-discord-recapturing-the-full-islamic-spirit-of-human-dignity/",description:"AbuSulayman reconsiders marital discord through Qur'anic ethics, human dignity, and the higher objectives of Islamic law. The study questions readings that neglect mutual care and justice within family life. It provides a concise example of maqasid-oriented interpretation in a modern discussion of Islamic law and ethics."},
  {file:"iiit-revitalizing-higher-education",title:"Revitalizing Higher Education in the Muslim World",author:"AbdulHamid A. AbuSulayman",publisher:"International Institute of Islamic Thought",isbn:"978-1-56564-877-7",language:"English",category:"Islamic Thought",pdf:"iiit-revitalizing-higher-education.pdf",cover:"iiit-revitalizing-higher-education-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/revitalizing-higher-education-in-the-muslim-world/",description:"This occasional paper addresses the renewal of higher education in Muslim societies. AbuSulayman links institutional reform to questions of knowledge, values, critical inquiry, and cultural responsibility. The work is useful for understanding modern Muslim debates about universities, educational purpose, and the relationship between intellectual development and civilisational renewal."},
  {file:"iiit-theory-islamic-art",title:"The Theory of Islamic Art",subtitle:"Aesthetic Concept and Epistemic Structure",author:"Idham Mohammed Hanash",publisher:"International Institute of Islamic Thought",language:"English",category:"Islamic Civilisation",pdf:"iiit-theory-islamic-art.pdf",cover:"iiit-theory-islamic-art-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/the-theory-of-islamic-art/",description:"Hanash examines Islamic art through aesthetic theory and epistemology rather than through formal description alone. The book considers artistic meaning, beauty, and the conceptual structures that connect visual culture to Islamic intellectual traditions. It is a focused contribution to the study of Islamic art, philosophy, and cultural history."},
  {file:"iiit-maqasid-made-simple",title:"Maqasid Al-Shari'ah Made Simple",author:"Mohammad Hashim Kamali",publisher:"International Institute of Islamic Thought",language:"English",category:"Islamic Jurisprudence",pdf:"iiit-maqasid-made-simple.pdf",cover:"iiit-maqasid-made-simple-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/maqasid-al-shariah-made-simple/",description:"Kamali introduces the higher objectives of Islamic law in clear, non-technical language. He explains their historical development, interpretive relevance, and role in contemporary legal and ethical reasoning. This short book is particularly suitable for students beginning work on maqasid al-shari'ah and its place within the wider discipline of usul al-fiqh."},
  {file:"iiit-justice-islam",title:"Justice in Islam",subtitle:"New Ethical Perspectives",author:"Ramon Harvey & Daniel Tutt",publisher:"International Institute of Islamic Thought",language:"English",category:"Islamic Thought",pdf:"iiit-justice-islam.pdf",cover:"iiit-justice-islam-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/justice-in-islam-new-ethical-perspectives/",description:"This volume considers justice through Qur'anic, prophetic, philosophical, and contemporary ethical perspectives. Its contributors examine how Islamic moral reasoning responds to social and political questions while remaining attentive to classical sources. The collection offers a useful entry point to current work on Islamic ethics, justice, and public responsibility."},
  {file:"iiit-postnormal-times-reader",title:"The Postnormal Times Reader",author:"Ziauddin Sardar (ed.)",publisher:"International Institute of Islamic Thought",language:"English",category:"Muslim Intellectual History",pdf:"iiit-postnormal-times-reader.pdf",cover:"iiit-postnormal-times-reader-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/the-postnormal-times-reader/",description:"Edited by Ziauddin Sardar, this reader gathers writing on uncertainty, complexity, and emerging challenges in contemporary societies. It connects Muslim intellectual discussion with wider debates about knowledge, futures, culture, and public life. The volume is valuable for researchers interested in postnormal theory and contemporary Muslim cultural and intellectual history."},
  {file:"iiit-essence-islamic-civilization",title:"The Essence of Islamic Civilization",author:"Ismail Raji Al-Faruqi",publisher:"International Institute of Islamic Thought",year:"2013",isbn:"978-1-56564-896-8",language:"English",category:"Islamic Civilisation",pdf:"iiit-essence-islamic-civilization.pdf",cover:"iiit-essence-islamic-civilization-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/the-essence-of-islamic-civilization/",description:"Al-Faruqi presents tawhid as the organising principle of Islamic civilisation. He considers how this central affirmation shapes religious belief, culture, knowledge, and collective life. The study is a compact primary text for students of Islamic thought and civilisation, especially those examining al-Faruqi's influential account of Islam's intellectual and cultural unity."},
  {file:"iiit-islam-muslim-civilization",title:"Islam and Muslim Civilization",subtitle:"A Supplementary Social Studies Unit for Sixth Grade",author:"Susan Douglass",publisher:"International Institute of Islamic Thought",year:"1995",isbn:"978-1-56564-889-0",language:"English",category:"Islamic Civilisation",pdf:"iiit-islam-muslim-civilization.pdf",cover:"iiit-islam-muslim-civilization-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/islam-and-muslim-civilization-a-supplementary-social-studies-unit-for-sixth-grade/",description:"Susan Douglass provides a source-based introduction to Islam and Muslim civilisation for classroom use. The unit covers core beliefs, historical development, and cultural contributions while encouraging critical use of historical evidence. Although designed for younger learners, it is also useful for studying approaches to Islamic history and public education."},
  {file:"iiit-wholeness-holiness-education",title:"Wholeness and Holiness in Education",subtitle:"An Islamic Perspective",author:"Zahra Al Zeera",publisher:"International Institute of Islamic Thought",year:"2001",isbn:"979-8-89193-128-2",language:"English",category:"Islamic Thought",pdf:"iiit-wholeness-holiness-education.pdf",cover:"iiit-wholeness-holiness-education-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/wholeness-and-holiness-in-education/",description:"Al Zeera critiques narrowly secular models of education and develops an Islamic account of integrated human development. The book brings together spirituality, knowledge, personal experience, and social responsibility in its discussion of learning. It is a substantial contribution to Islamic educational philosophy and the modern history of Muslim intellectual reform."},
  {file:"iiit-reviving-balance-quran-sunnah",title:"Reviving the Balance",subtitle:"The Authority of the Qur'an and the Status of the Sunnah",author:"Taha Jabir Alalwani",publisher:"International Institute of Islamic Thought",year:"2017",isbn:"978-1-56564-878-4",language:"English",category:"Hadith Studies",pdf:"iiit-reviving-balance-quran-sunnah.pdf",cover:"iiit-reviving-balance-quran-sunnah-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/reviving-the-balance-the-authority-of-the-quran-and-the-status-of-the-sunnah/",description:"Alalwani studies the relationship between the Qur'an and Sunnah, with attention to authority, transmission, interpretation, and legal application. He argues for a balanced approach that avoids treating the two sources as rivals. The book is a substantial resource for students of hadith, Qur'anic interpretation, and modern debates about Islamic methodology."},
  {file:"iiit-ethics-assisted-reproductive-medicine",title:"Ethics of Assisted Reproductive Medicine",author:"Sharmin Islam",publisher:"International Institute of Islamic Thought",year:"2014",isbn:"978-1-56564-535-6",language:"English",category:"Islamic Ethics",pdf:"iiit-ethics-assisted-reproductive-medicine.pdf",cover:"iiit-ethics-assisted-reproductive-medicine-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/ethics-of-assisted-reproductive-medicine-a-comparative-study-of-western-secular-and-islamic-bioethics/",description:"Sharmin Islam compares Islamic and secular approaches to reproductive medicine. The study addresses technologies such as artificial insemination and surrogacy through ethical principles drawn from the Qur'an and Sunnah. It is an academically focused resource for Islamic bioethics and for research on how juristic reasoning engages contemporary medical practice."},
  {file:"iiit-contemporary-approaches-quran-sunnah",title:"Contemporary Approaches to the Qur'an and Sunnah",author:"Mahmoud Ayoub (ed.)",publisher:"International Institute of Islamic Thought",year:"2012",isbn:"978-1-56564-530-1",language:"English",category:"Qur'anic and Hadith Studies",pdf:"iiit-contemporary-approaches-quran-sunnah.pdf",cover:"iiit-contemporary-approaches-quran-sunnah-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/contemporary-approaches-to-the-quran-and-sunnah/",description:"Edited by Mahmoud Ayoub, this collection addresses contemporary scholarship on the Qur'an and Sunnah as the central sources of Muslim faith, ethics, and law. It brings modern interpretive questions into conversation with classical traditions. The volume is valuable for students seeking a multi-author introduction to current approaches in Islamic studies."},
  {file:"iiit-islamic-theory-international-relations",title:"Towards an Islamic Theory of International Relations",author:"AbdulHamid A. AbuSulayman",publisher:"International Institute of Islamic Thought",year:"1993",isbn:"978-1-56564-786-2",language:"English",category:"Islamic Thought",pdf:"iiit-islamic-theory-international-relations.pdf",cover:"iiit-islamic-theory-international-relations-cover.jpg",access:"Publisher-designated open access",sourceUrl:"https://iiit.org/en/book/towards-an-islamic-theory-of-international-relations-new-directions-%e2%80%8bfor-methodology-and-thought/",description:"AbuSulayman develops an Islamic approach to international relations that returns to the Qur'an and Sunnah while engaging modern social-scientific methodology. The book considers world order, human dignity, and political community through Islamic intellectual resources. It is an important historical text for research on Islam and international relations theory."}
];
const libraryBatchSix = [
["anthropomorphic-god","Anthropomorphic Depictions of God","Zulfiqar Ali Shah","Islamic Thought"],["approaching-international-relations","Approaching the Discipline of International Relations","Nadia Mahmoud Mostafa","Islamic Thought"],["authentication-hadith","Authentication of Hadith: Redefining the Criteria","Israr Ahmad Khan","Hadith Studies"],["collective-ijtihad","Collective Ijtihad: Regulating Fatwa in Postnormal Times","Hossam Sabry Othman","Islamic Jurisprudence"],["emerging-epistemologies","Emerging Epistemologies","Ziauddin Sardar (ed.)","Muslim Intellectual History"],["islamic-law-ethics","Islamic Law and Ethics","David R. Vishanoff","Islamic Jurisprudence"],["islamic-legal-methodology","Islamic Legal Methodology: A New Perspective on Usul al-Fiqh","Ahmad Kazemi Moussavi & Hamid Mavani","Islamic Jurisprudence"],["mapping-intellectual-building","Mapping Intellectual Building and the Construction of Thought and Reason","Fathi Hasan Malkawi","Islamic Thought"],["maqasid-civilizational-perspective","Maqasid Al-Shari'ah: A Civilizational Perspective","Mazen Hashem","Islamic Thought"],["maqasid-biomedicine","Maqasid Al-Shariah and Biomedicine","Aasim I. Padela","Islamic Ethics"],["muslim-societies-postnormal","Muslim Societies in Postnormal Times","Ziauddin Sardar, Jordi Serra & Scott Jordan","Muslim Intellectual History"],["parent-child-relations","Parent-Child Relations: A Guide to Raising Children","Hisham Altalib, Abdulhamid Abusulayman & Omar Altalib","Islamic Thought"],["preserving-unity","Preserving Unity and Avoiding Division","Taha Jabir Al-Alwani","Islamic Thought"],["public-policy-maqasid","Public Policy: Beyond Traditional Jurisprudence","Basma I. Abdelgafar","Islamic Jurisprudence"],["agency-rationality-morality","Agency, Rationality, and Morality: A Qur'anic View of Man","Mona Abul-Fadl","Qur'anic Studies"],["apostasy-historical-analysis","Apostasy in Islam: A Historical and Scriptural Analysis","Taha Jabir Al-Alwani","Islamic Thought"],["bridging-divide","Bridging The Divide: Beyond The Ethics Of Disagreement","Taha Jabir Al-Alwani","Islamic Thought"],["contemplation-psychospiritual","Contemplation: An Islamic Psychospiritual Study","Malik Badri","Islamic Thought"],["economic-doctrines-islam","Economic Doctrines of Islam","Irfan Ul Haq","Islamic Thought"],["fine-differences","Fine Differences: The Al-Alwani Muslim-Christian Lectures 2010-2017","Richard J. Jones","Muslim Intellectual History"]
].map(([file,title,author,category])=>({file,title,author,category,publisher:"International Institute of Islamic Thought",language:"English",pdf:`iiit-${file}.pdf`,cover:`iiit-${file}-cover.jpg`,access:"Publisher-designated open access",description:"A publisher-authorized open-access scholarly book selected for the AQIRI Library after checking the publisher record, full local PDF, and official cover image.",sourceUrl:`https://iiit.org/en/book/${file}/`}));
window.AQIRILibrary = Array.from(new Map([...libraryCore, ...libraryBatchTwo, ...libraryBatchThree, ...libraryBatchFour, ...libraryBatchFive, ...libraryBatchSix].map((book) => [book.file, book])).values());
